import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleCheckBig,
  Clock,
  Coins,
  Eye,
  EyeOff,
  FileChartLine,
  Gem,
  Gift,
  Heart,
  HelpCircle,
  Home,
  Info,
  KeyRound,
  LayoutDashboard,
  Loader2,
  Lock,
  LogOut,
  Megaphone,
  Menu,
  Minus,
  Moon,
  MoreHorizontal,
  OctagonX,
  PanelLeft,
  PanelsTopLeft,
  Phone,
  Plus,
  PlusCircle,
  RefreshCw,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Star,
  Sun,
  TriangleAlert,
  User,
  Users,
  Wallet,
  X,
} from "lucide-react";
import React from "react";
import { cn } from "@/lib/utils";

const ICON_MAP = {
  add: <Plus />,
  "add-circle": <PlusCircle />,
  alert: <AlertCircle />,
  analytics: <BarChart3 />,
  "arrow-left": <ArrowLeft />,
  "arrow-right": <ArrowRight />,
  audit: <ShieldAlert />,
  "badge-check": <BadgeCheck />,
  "bell-ring": <BellRing />,
  calendar: <Calendar />,
  campaign: <Wallet />,
  check: <Check />,
  "check-circle": <CircleCheckBig />,
  "chevron-down": <ChevronDown />,
  "chevron-left": <ChevronLeft />,
  "chevron-right": <ChevronRight />,
  "chevron-up": <ChevronUp />,
  "circle-check": <CircleCheck />,
  "circle-check-big": <CircleCheckBig />,
  clock: <Clock />,
  close: <X />,
  contribution: <Coins />,
  dashboard: <LayoutDashboard />,
  eye: <Eye />,
  "eye-off": <EyeOff />,
  favorite: <Heart />,
  filter: <SlidersHorizontal />,
  gem: <Gem />,
  gift: <Gift />,
  group: <Users />,
  help: <HelpCircle />,
  home: <Home />,
  info: <Info />,
  key: <KeyRound />,
  loading: <Loader2 className="animate-spin" />,
  lock: <Lock />,
  "log-out": <LogOut />,
  megaphone: <Megaphone />,
  member: <User />,
  menu: <Menu />,
  minus: <Minus />,
  moon: <Moon />,
  "more-horizontal": <MoreHorizontal />,
  notification: <Bell />,
  "octagon-x": <OctagonX />,
  "panel-left": <PanelLeft />,
  "panels-top-left": <PanelsTopLeft />,
  phone: <Phone />,
  refresh: <RefreshCw />,
  report: <FileChartLine />,
  search: <Search />,
  settings: <Settings />,
  "shield-check": <ShieldCheck />,
  smartphone: <Smartphone />,
  star: <Star />,
  sun: <Sun />,
  transaction: <Banknote />,
  "triangle-alert": <TriangleAlert />,
} as const;

type IconName = keyof typeof ICON_MAP;

interface IconLibraryProps {
  name: IconName;
  className?: string;
  strokeWidth?: number;
}

const IconLibrary: React.FC<IconLibraryProps> = ({ name, className, strokeWidth }) => {
  const iconElement = ICON_MAP[name];
  return React.cloneElement(iconElement, {
    className: cn(iconElement.props.className, className),
    strokeWidth: strokeWidth ?? iconElement.props.strokeWidth,
  });
};

export default IconLibrary;
export type { IconLibraryProps, IconName };
