export const HR_URLS = {
  attendanceMe: "/hr/attendance/me",
  attendanceRegister: "/hr/attendance/register",
  attendanceSummary: "/hr/attendance/summary",
  attendanceSummaryPdf: "/hr/attendance/summary/pdf",
  attendanceAdjustment: (userId: string, date: string) =>
    `/hr/attendance/adjustments/${userId}/${date}`,
  attendanceAdjustments: "/hr/attendance/adjustments",
  attendanceToday: "/hr/attendance/today",
  clockIn: "/hr/reports/clock-in",
  clockOut: "/hr/reports/clock-out",
  confirmReport: (reportId: string) => `/hr/reports/${reportId}/confirm`,
  employeeMeetings: (userId: string) => `/hr/employees/${userId}/meetings`,
  employeeReports: (userId: string) => `/hr/reports/${userId}`,
  employeeSchedule: (userId: string) => `/hr/schedule/employees/${userId}`,
  meeting: (meetingId: string) => `/hr/meetings/${meetingId}`,
  meetingAttendance: (meetingId: string) => `/hr/meetings/${meetingId}/attendance`,
  meetingCancel: (meetingId: string) => `/hr/meetings/${meetingId}/cancel`,
  meetingCheckIn: (meetingId: string) => `/hr/meetings/${meetingId}/check-in`,
  meetingRsvp: (meetingId: string) => `/hr/meetings/${meetingId}/rsvp`,
  meetings: "/hr/meetings",
  meetingsAll: "/hr/meetings/all",
  location: (locationId: string) => `/hr/locations/${locationId}`,
  locationArchive: (locationId: string) => `/hr/locations/${locationId}/archive`,
  locationDefault: (locationId: string) => `/hr/locations/${locationId}/default`,
  locationRestore: (locationId: string) => `/hr/locations/${locationId}/restore`,
  locations: "/hr/locations",
  schedule: "/hr/schedule",
  scheduleOverride: (overrideId: string) => `/hr/schedule/overrides/${overrideId}`,
  scheduleOverrides: "/hr/schedule/overrides",
} as const;
